OE_Platform/urls.py
# from wagtail.wagtailadmin import urls as wagtailadmin_urls
# from wagtail.wagtaildocs import urls as wagtaildocs_urls
# from wagtail.wagtailcore import urls as wagtail_urls
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from . import views
#from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'^experiment/', include('experiment.urls', namespace='experiment')),
    
#     url(r'^cms/', include(wagtailadmin_urls)),
#     url(r'^documents/', include(wagtaildocs_urls)),
#     url(r'^pages/', include(wagtail_urls)),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_old_views
from OE_Platform import views as auth_views
from . import views 

app_name = "account"

urlpatterns = [
     url(r'^$', views.dashboard, name='dashboard'),
     #url(r'^login/$', views.Login(template_name='account/login.html'), name='login'),
     #url(r'^logout/$', auth_views.LogoutView.as_view(template_name='account/logged_out.html'), name='logout'),    
     url(r'^register/$', views.RegisterAccount.as_view(), name='register'),
     url(r'^register_done/$', views.RegisterAccountDoneView.as_view(), name='register_done'),
#These following URLs will allow us to change passwords
     url(r'^password_change/$', auth_views.PasswordChangeView.as_view(template_name='account/registration/password_change_form.html'), name='password_change' ),
     url(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='account/registration/password_change_done.html'), name='password_change_done'),
#URLS for Restoring the password 
     url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name='account/registration/password_reset_form.html'), name='password_reset'),
     url(r'^password-reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='account/registration/password_reset_done.html'), name='password_reset_done'),
     url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(template_name='account/registration/password_reset_confirm.html'), name='password_reset_confirm'),
     url(r'^password-reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='account/registration/password_reset_complete.html'), name='password_reset_complete'),

#Researcher URLS
#Create Account
     url(r'^researcher/register/$', views.RegisterAccount.as_view(), name='reseacher_register'),
     
    
     #url(r'^edit/$', views.AccountUpdateView.as_view(), name='edit'),
     #url(r'^login/$', views.user_login, name='login'),
     url(r'^login/$', auth_old_views.login,{'template_name': 'account/login.html'}, name='login'),
     url(r'^logout/$', auth_old_views.logout, {'template_name': 'account/logged_out.html'}, name='logout'),
    # url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
    
    
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^user_remove/$', views.accountRemoval, name='account_remove'),
    ]


# OBSOLETE CODE 

#     #These following URLs will allow us to change passwords
#     url(r'^password-change/$', auth_views.password_change, name='password_change'),
#     url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),
#     
#     #URLS for Restoring the password 
#     url(r'^password-reset/$', auth_views.password_reset, name='password_reset'),
#     url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
#     url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
#     url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
#     
#     #URL for user-participant creation
#     url(r'^register/$', views.register, name='register'),

#     
    
     
#     
#     #Researcher URLS
#         #Create Account
#     url(r'^researcher/register/$', views.register, name='reseacher_register'),
#         #researcher portal

experiment/urls.py
from django.conf.urls import url
from . import views

app_name = "experiment"

urlpatterns = [
    
    # Experiment URLS
    url(r'^researcher/experiment_list/$', views.ExperimentListView.as_view(), name='exp_list'),
    url(r'^researcher/experiment_create/$', views.ExperimentCreateView.as_view(), name='exp_create'),
    url(r'^researcher/experiment_list/(?P<pk>\d+)/$', views.ExperimentDetailView.as_view(), name='exp_detail'),
    url(r'^researcher/experiment_list/(?P<epk>\d+)/participant_list/$', views.ExperimentUserListView.as_view(), name='exp_user_list'),
    url(r'^researcher/experiment_list/(?P<epk>\d+)/participant_list/(?P<pk>\w+)/$', views.ExperimentUserQueryView.as_view(), name='exp_user_query'),
    url(r'^researcher/experiment_list/update/(?P<pk>\d+)/$', views.ExperimentUpdateView.as_view(), name='exp_update'),
    url(r'^researcher/experiment_list/delete/(?P<pk>\d+)/$', views.ExperimentDeleteView.as_view(), name='exp_delete'),
    url(r'^experiment_list_public/$', views.ExperimentPublicListView.as_view(), name='exp_list_public'),
    url(r'^experiment_list_public/(?P<pk>\d+)/$', views.ExperimentPublicTest.as_view(), name='exp_test'),

    url(r'^researcher/experiment_list/(?P<epk>\d+)/file_list/$', views.FileListView.as_view(), name='file_list'),
    #url(r'^researcher/experiment_list/file_create/$', views.FileCreateView.as_view(), name='file_create'),
    url(r'^researcher/experiment_list/(?P<epk>\d+)/file_list/delete/(?P<pk>\d+)/$', views.FileDeleteView.as_view(), name='file_delete'),
    url(r'^ajax/post/$', views.PostData, name='post_data'),
   # url(r'^debug/$', views.some_streaming_csv_view, name='csv_view'),
    url(r'^debug1/$', views.fullTableToCSV, name='csv'),

    ]

templates/base.html
 <!DOCTYPE html>
 {% load staticfiles %}
 {% load bootstrap3 %}
 <html>
   <head>
     <title>{% block title %}{% endblock %}</title>
     <link href="{% static "css/base.css" %}" rel="stylesheet">
	 {% block stylesheet %}{% endblock %}
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
     
   </head>
   <body>
       <nav class='nav navbar navbar-default bg-faded' role='navigation' id='navbar'>
       		<div class="container-fluid">
       			<div class="navbar-header text-center">
		       		{% if user.is_authenticated %}<a class="navbar-brand" href="{% url 'account:dashboard' %}">
		       		{% else %}<a class="navbar-brand" href="{% url 'home' %}">
		       		{% endif %}
		       		THE OE PLATFORM</a>
	       		</div>
		       		<ul class="nav navbar-nav nav-pills nav-stacked">
			       		<li><a href="{% url 'home' %}" class="btn btn-simple">Home</a></li>
			       		{% if user.is_participant %}
			       			<li><a href="{% url "account:edit" %}" class="btn btn-simple">Profile</a></li>
			       		{% endif %}
			       		{% if user.is_researcher %}
			       			<li><a href="{% url "experiment:exp_list" %}" class="btn btn-simple">My Experiments</a></li>
			       		{% endif %}
			       		<li><a href="{% url "experiment:exp_list_public" %}" class="btn btn-simple">Experiments</a></li>
		       		</ul>
		       		<ul class="nav navbar-nav navbar-right nav-stacked">
		       			{% if user.is_authenticated %}
		        		 	<p class='navbar-text text-center'>Signed in as {{ user.get_username }},</p>
		        		 	<li> <a href="{% url "account:logout" %}" class="btn btn-simple">Logout?</a></li>
		      		 	{% else %}
		        			 <li><a href="{% url "account:login" %}" class="btn btn-simple">Log-in</a></li>
		        			 <li><a href="{% url "account:register" %}">Sign Up</a></li>
		       			{% endif %}
		       		</ul>
	       		</div>
       </nav>
	
{% if messages %}
	<ul class="messages">
		{% for message in messages %}
			<li class={{ message.tags }}>
			{{ message|safe }}
				<a href="" class="close">✖</a>
			</li>
		{% endfor %}
	</ul>
{% endif %}
     <div id="content">
       {% block content %}{% endblock %}
     </div>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  	 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	 <script src="{% static 'js/experiment.js' %}"></script>
     {% block javascript %}{% endblock %}
   </body>
   </html>

templates/index.html
{% extends "base.html" %}
{% block title %}HomePage{% endblock %}

{% block content %}
<div class="container">
	<h1>Home</h1>
	<p>Welcome to the OE PLATFORM </p>
	
</div>
{% endblock %}