OE_Platform/urls.py
# from wagtail.wagtailadmin import urls as wagtailadmin_urls
# from wagtail.wagtaildocs import urls as wagtaildocs_urls
# from wagtail.wagtailcore import urls as wagtail_urls
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from . import views
#from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'^experiment/', include('experiment.urls', namespace='experiment')),
    
#     url(r'^cms/', include(wagtailadmin_urls)),
#     url(r'^documents/', include(wagtaildocs_urls)),
#     url(r'^pages/', include(wagtail_urls)),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_old_views
from OE_Platform import views as auth_views
from . import views 

app_name = "account"

urlpatterns = [
     url(r'^$', views.dashboard, name='dashboard'),
     #url(r'^login/$', views.Login(template_name='account/login.html'), name='login'),
     #url(r'^logout/$', auth_views.LogoutView.as_view(template_name='account/logged_out.html'), name='logout'),    
     url(r'^register/$', views.RegisterAccount.as_view(), name='register'),
     url(r'^register_done/$', views.RegisterAccountDoneView.as_view(), name='register_done'),
#These following URLs will allow us to change passwords
     url(r'^password_change/$', auth_views.PasswordChangeView.as_view(template_name='account/registration/password_change_form.html'), name='password_change' ),
     url(r'^password-change/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='account/registration/password_change_done.html'), name='password_change_done'),
#URLS for Restoring the password 
     url(r'^password-reset/$', auth_views.PasswordResetView.as_view(template_name='account/registration/password_reset_form.html'), name='password_reset'),
     url(r'^password-reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='account/registration/password_reset_done.html'), name='password_reset_done'),
     url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.PasswordResetConfirmView.as_view(template_name='account/registration/password_reset_confirm.html'), name='password_reset_confirm'),
     url(r'^password-reset/complete/$', auth_views.PasswordResetCompleteView.as_view(template_name='account/registration/password_reset_complete.html'), name='password_reset_complete'),

#Researcher URLS
#Create Account
     url(r'^researcher/register/$', views.RegisterAccount.as_view(), name='reseacher_register'),
     
    
     #url(r'^edit/$', views.AccountUpdateView.as_view(), name='edit'),
     #url(r'^login/$', views.user_login, name='login'),
     url(r'^login/$', auth_old_views.login,{'template_name': 'account/login.html'}, name='login'),
     url(r'^logout/$', auth_old_views.logout, {'template_name': 'account/logged_out.html'}, name='logout'),
    # url(r'^logout-then-login/$', auth_views.logout_then_login, name='logout_then_login'),
    
    
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^user_remove/$', views.accountRemoval, name='account_remove'),
    ]


# OBSOLETE CODE 

#     #These following URLs will allow us to change passwords
#     url(r'^password-change/$', auth_views.password_change, name='password_change'),
#     url(r'^password-change/done/$', auth_views.password_change_done, name='password_change_done'),
#     
#     #URLS for Restoring the password 
#     url(r'^password-reset/$', auth_views.password_reset, name='password_reset'),
#     url(r'^password-reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
#     url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
#     url(r'^password-reset/complete/$', auth_views.password_reset_complete, name='password_reset_complete'),
#     
#     #URL for user-participant creation
#     url(r'^register/$', views.register, name='register'),

#     
    
     
#     
#     #Researcher URLS
#         #Create Account
#     url(r'^researcher/register/$', views.register, name='reseacher_register'),
#         #researcher portal

experiment/urls.py
from django.conf.urls import url
from . import views

app_name = "experiment"

urlpatterns = [
    
    # Experiment URLS
    url(r'^researcher/experiment_list/$', views.ExperimentListView.as_view(), name='exp_list'),
    url(r'^researcher/experiment_create/$', views.ExperimentCreateView.as_view(), name='exp_create'),
    url(r'^researcher/experiment_list/(?P<pk>\d+)/$', views.ExperimentDetailView.as_view(), name='exp_detail'),
    url(r'^researcher/experiment_list/(?P<epk>\d+)/participant_list/$', views.ExperimentUserListView.as_view(), name='exp_user_list'),
    url(r'^researcher/experiment_list/(?P<epk>\d+)/participant_list/(?P<pk>\w+)/$', views.ExperimentUserQueryView.as_view(), name='exp_user_query'),
    url(r'^researcher/experiment_list/update/(?P<pk>\d+)/$', views.ExperimentUpdateView.as_view(), name='exp_update'),
    url(r'^researcher/experiment_list/delete/(?P<pk>\d+)/$', views.ExperimentDeleteView.as_view(), name='exp_delete'),
    url(r'^experiment_list_public/$', views.ExperimentPublicListView.as_view(), name='exp_list_public'),
    url(r'^experiment_list_public/(?P<pk>\d+)/$', views.ExperimentPublicTest.as_view(), name='exp_test'),

    url(r'^researcher/experiment_list/(?P<epk>\d+)/file_list/$', views.FileListView.as_view(), name='file_list'),
    #url(r'^researcher/experiment_list/file_create/$', views.FileCreateView.as_view(), name='file_create'),
    url(r'^researcher/experiment_list/(?P<epk>\d+)/file_list/delete/(?P<pk>\d+)/$', views.FileDeleteView.as_view(), name='file_delete'),
    url(r'^ajax/post/$', views.PostData, name='post_data'),
   # url(r'^debug/$', views.some_streaming_csv_view, name='csv_view'),
    url(r'^debug1/$', views.fullTableToCSV, name='csv'),

    ]

experiment/forms.py
from django import forms
from .models import Experiment, Attachment
from multiupload.fields import MultiFileField

class UploadForm(forms.Form):
    files =  MultiFileField(min_num=0, max_num=3, max_file_size=1024*1024*5, required=False)
      
class ExperimentForm(forms.ModelForm):
     class Meta:
        model = Experiment
        fields = ('name', 'description', 'query')
        
     files =  MultiFileField(min_num=0, max_num=3, max_file_size=1024*1024*5, required=False)

class ExperimentFormBasic(forms.ModelForm):
     class Meta:
        model = Experiment
        fields = ('name', 'description', 'is_Published')
        
  
#ExperimentFormSet = forms.inlineformset_factory(Experiment, Attachment)
                       
#      def clean_name(self):
#         name = self.cleaned_data['name']
#         valid_extensions = ['css', 'js', 'html']
#         print(name.rsplit('.', 1))
#         extension = name.rsplit('.', 1)[1].lower()
#         if extension not in valid_extensions:
#             raise forms.ValidationError('The given file isn\'t a text file')
#         return name
    
#      def save(self, commit=True):
#         instance = super(ExperimentForm, self).save(commit)
#         for each in self.cleaned_data['files']:
#             Attachment.objects.create(file=each, experiment=instance)
# 
#         return instance
#     
#      def save(self, commit=False):
#        instance = super(ExperimentForm, self).save(commit)
#        for each in self.cleaned_data['files']:
#            Attachment.objects.create(file=each)
#  
#        return instance

experiment/views.py
#from django.shortcuts import render
from django.views.generic import (CreateView, UpdateView, DeleteView, DetailView, ListView, TemplateView)
#from django.urls import reverse
# import io
# import sys
# Create your views here.
# from .models import *
# from .forms import *
# from django.shortcuts import get_object_or_404
# from OE_Platform.mixins import AjaxableResponseMixin
# from django.views.generic.base import TemplateResponseMixin
# from django.views.generic.edit import FormMixin, BaseCreateView
# from django.views.generic.list import BaseListView
from .models import Experiment, Attachment, Trial
from .forms import ExperimentForm, ExperimentFormBasic
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.http import Http404
from django.utils.decorators import method_decorator
import os
import json
from OE_Platform.settings import MEDIA_ROOT
from account.models import AnonUserCounter

#from psycopg2 import sql
import psycopg2
from psycopg2.extensions import AsIs
from django.db import connection
#from django.utils.text import slugify
import csv
from django.db.models import F
       
def experiment_create_directory_path(user, experiment):
    # folder will be created on experiment creation media/uploads/researcher_<id>/<experiment>/
    dr = os.path.join(user.home_directory, experiment.name) 
    experiment.home_directory = dr
    os.mkdir(os.path.join(MEDIA_ROOT, dr))
     
def belongsToResearcher(researcher, expID):
    """
        Checks if object belongs to researcher, if num==0, checks experiment, if num==1 checks attachment
    """
    try:
        researcher.experiments.get(id=expID)
        return True
    except:
        return False
    
def multipleFilesUpload(form, exp): #removed instance
    for each in form.cleaned_data['files']:
        Attachment.objects.create(file=each, experiment=exp)
        
class CSVResponseMixin(object):
    csv_filename = 'csvfile.csv'

    def get_csv_filename(self):
        return self.csv_filename

    def render_to_csv(self, data):
        response = HttpResponse(content_type='text/csv')
        cd = 'attachment; filename="{0}"'.format(self.get_csv_filename())
        response['Content-Disposition'] = cd

        writer = csv.writer(response)
        for row in data:
            writer.writerow(row)

        return response        
    
# class CSVResponseMixin(object):
#     """
#     A generic mixin that constructs a CSV response from the context data if
#     the CSV export option was provided in the request.
#     """
#     def render_to_response(self, context, **response_kwargs):
#         """
#         Creates a CSV response if requested, otherwise returns the default
#         template response.
#         """
#         # Sniff if we need to return a CSV export
#         if 'csv' in self.request.GET.get('export', ''):
#             response = HttpResponse(content_type='text/csv')
#             response['Content-Disposition'] = 'attachment; filename="%s.csv"' % slugify(context['title'])
# 
#             writer = csv.writer(response)
#             # Write the data from the context somehow
#             for item in context['items']:
#                 writer.writerow(item)
# 
#             return response
#         # Business as usual otherwise
#         else:
#             return super(CSVResponseMixin, self).render_to_response(context, **response_kwargs)      
          
# class FormAndListView(BaseCreateView, BaseListView, TemplateResponseMixin):
#     def get(self, request, *args, **kwargs):
#         formView = BaseCreateView.get(self, request, *args, **kwargs)
#         listView = BaseListView.get(self, request, *args, **kwargs)
#         formData = formView.context_data['form']
#         listData = listView.context_data['object_list']
#         return render_to_response('textfrompdf/index.html', {'form' : formData, 'all_PDF' : listData}, context_instance=RequestContext(request))
    
# class FormListView(FormMixin, ListView):
#     """
#         Helps produce a form and list in one view
#     """
#     def get(self, request, *args, **kwargs):
#         # From ProcessFormMixin
#         form_class = self.get_form_class()
#         self.form = self.get_form(form_class)

#         # From BaseListView
#         self.object_list = self.get_queryset()
#         allow_empty = self.get_allow_empty()
#         if not allow_empty and len(self.object_list) == 0:
#             raise Http404(_(u"Empty list and '%(class_name)s.allow_empty' is False.")
#                           % {'class_name': self.__class__.__name__})

#         context = self.get_context_data(object_list=self.object_list, form=self.form)
#         return self.render_to_response(context)

#     def post(self, request, *args, **kwargs):
#         return self.get(request, *args, **kwargs)
    
class ExperimentListView(ListView):
    """
        Using Django's generic ListView which displays all experiments in list format
    """
    context_object_name = 'experiments'
    model = Experiment
    
    
#     def researcherPortal(request):  
#             return render(request, 'account/experiment_list.html', {'section': 'experiment_list'})
   
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_researcher:
            return super(ExperimentListView, self).dispatch(*args, **kwargs)
        else:
            return HttpResponse(Http404("You are not a researcher"))
    
class ExperimentDetailView(DetailView):
    """
        Using Django's generic DetailView which displays the detail(js code, data published, etc) of an experiment
    """
    context_object_name = 'experiment'
    model = Experiment
    
    def get_context_data(self, **kwargs):
        context = super(ExperimentDetailView, self).get_context_data(**kwargs)
        context['attachments'] = DetailView.get_object(self).attachment_set.all() #get all attachments of detailview object (experiment)
        return context   
          
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_researcher and belongsToResearcher(self.request.user, DetailView.get_object(self).id):
            return super(ExperimentDetailView, self).dispatch(*args, **kwargs)
        else:
            return HttpResponse(Http404("You are not a researcher or experiment does not belong to you"))

def getAnonList(eID):
    return eID
from account.models import User   
     
class ExperimentUserListView(ListView):
    """
        ListView that displays all users that completed the experiment
    """
    context_object_name = 'participant'
    #model = User
    #query_set = User.objects.filter(experiments=ExperimentUserListView.kwargs.get('epk', ''))

    template_name = 'Experiment/user_list.html'
    
    def get_queryset(self):
        return User.objects.filter(experiments=self.kwargs.get('epk', ''))

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        print("testing 1-2")
        print(self.kwargs.get('epk', ''))
        if self.request.user.is_researcher and belongsToResearcher(self.request.user, self.kwargs.get('epk', '')):
            return super(ExperimentUserListView, self).dispatch(*args, **kwargs)
        else:
            return HttpResponse(Http404("You are not a researcher or experiment does not belong to you"))    
       
        #Must also get anonymous users...how? 
    def get_context_data(self, **kwargs):
        context = super(ExperimentUserListView, self).get_context_data(**kwargs)
        context['anon_list'] = Trial.objects.filter(experiment=self.kwargs.get('epk', ''))
        return context   

class ExperimentUserQueryView(CSVResponseMixin, TemplateView):
    """
        Query of the participant data for that specific experiment, with the option to export CSV file
    """
    template_name = "experiment/user_query.html"
        
    def get_context_data(self, **kwargs):
        context = super(ExperimentUserQueryView, self).get_context_data(**kwargs)
        eID = self.kwargs.get('epk', '')
        uID = self.kwargs.get('pk', '')
        table_name = "exp" + eID + "_" + uID
        query = """table {};"""
        context['data'] = QueryData(table_name, query) 
        context['table'] = table_name
        return context   
          
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_researcher and belongsToResearcher(self.request.user, self.kwargs.get('epk', '')):
            return super(ExperimentUserQueryView, self).dispatch(*args, **kwargs)
        else:
            return HttpResponse(Http404("You are not a researcher or experiment does not belong to you"))
        
class ExperimentCreateView(CreateView):
    """
        Using Django's generic CreateView which produces a form that will help a researcher produce an experiment. Once form is filled out, experiment model is saved in database.
    """
    #fields = ('name', 'description')
    model = Experiment
    form_class = ExperimentForm
    template_name = 'Experiment/experiment_form.html'
    success_url = reverse_lazy("experiment:exp_list")
     
    def form_valid(self, form):
        print("----====== ---======---- TESTING DEBUGGING ----====== ----======----")
        print("CheckPoint")
     
        print("----====== ---======---- ENDING DEBUGGING ----====== ----======----")
             
        exp = form.save(commit=False)
        exp.created_By = self.request.user.username
        experiment_create_directory_path(self.request.user, exp)
        exp.save()
        multipleFilesUpload(form, exp, self.request) # use this later 
        self.request.user.experiments.add(exp)
        self.request.user.save() 
        messages.success(self.request, 'file added successfully')

experiment/templates/experiment/attachment_list.html
{% extends "base.html" %}
{% block title %}File List View{% endblock %}
{% load static %}
{% load bootstrap3 %}
{% block content %}

<div class="container">
	<h1>File List</h1>
	
	{% if not attachments %}
		<p>There are no files, please upload a file</p>
		<p>Upload a file?</p>
	{% endif %}
	<div style="padding:15px;">
	
		<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
    	{% bootstrap_form form %}
		<button type="submit" name="upload_file" class="btn btn-default bt-sm"><span class="glyphicon glyphicon-plus"></span></button>	
</div>
		</form>		
			{% if attachments %}
				<div class="container">
				
					  <table id='tb1' class="table table-bordered table-hover">
						<thead>
						<tr>
							<th>File Name</th>
							<th> Delete </th>
						</tr>
						</thead>
						<tbody>
						{% for file in attachments %}
						<form action="{% url 'experiment:file_delete' epk file.id %}" method="post" enctype="multipart/form-data">
						{% csrf_token %}	
							<td>{{ file.filename }}</td>
							<td><button type="submit" class="btn btn-default bt-sm"><span class="glyphicon glyphicon-trash"></span></button></td>
						</tr>
						</form> 
						{% endfor%}
						</tbody>
					</table>
				</div>
			{% endif %}
			

		
</div>
{% endblock %}

experiment/templates/experiment/experiment.html
{% extends "base.html" %}

{% block title %} Experiment{% endblock %}
{% block extraSrc %} <!-- {{ experiment.js_Code_Header|safe|escape }} --> {% endblock %}

{% block content %}

<div class="iframe">
<iframe src="{{ htmlFile.file.url }}" allowfullscreen = "true">
  <p>Your browser does not support iframes.</p>
</iframe>  
</div>

<script>
function PostData(tdata){
	console.log("hi");
	console.log(tdata);
	td = JSON.stringify(tdata);
	expID = {{ experiment.id }}
	//get data
	
	//var data = document.getElementById('iframe').contentWindow.data;
	      $.ajax({
			type: "POST",
	        url: '/experiment/ajax/post/', //for post urls, there must have a slash at the end :S
	        data: {'data': td , 'csrfmiddlewaretoken': '{{ csrf_token }}', "expID":expID},
	        dataType: 'json',
	        async: true,
	        success: function (data) {
	            alert(data);
	        }
	      });
}

</script>
<!--  parent.PostData(tdata) within the iframe, used to send data out -->

{% endblock %}

experiment/templates/experiment/experiment_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete {{ experiment }}?</h1>
<form method="post">
	{% csrf_token %}
	<input type="submit" class='btn btn-danger' value="Delete">
	<a href="{% url "experiment:exp_detail" pk=experiment.pk %}">Cancel</a>
</form>

{% endblock %}

experiment/templates/experiment/experiment_detail.html
{% extends "base.html" %}

{% block title %} Experiment Detail View {% endblock %}

{% block content %}
<div class="container">
<h1>Detail View of Experiment</h1>
		<table class="table">
		<thead><tr>
		<th>Name</th>
		<th>Owner</th>
		<th>Description</th>
		</tr></thead>
		<tbody class="non-bolded">
		<tr>
		<th>{{ experiment.name }}</th>
		<th>{{ experiment.created_By }}</th>
		<th> {{ experiment.description }}</th>
		<th><a href="{% url 'experiment:exp_update' pk=experiment.pk %}" class="btn btn-warning">Update</a>
		</th>
		<th><a href="{% url 'experiment:exp_delete' pk=experiment.pk %}" class="btn btn-danger">Delete</a>
		</th>
		</tr>
		</tbody>
	<!-- 
		
		<thead><tr><th>Uploaded Files</th></tr></thead>
		
		<tbody>
		
		</tbody>
	</table> -->
	{% if attachments %}
	<table class="table table-striped">
    <thead>
      <tr>
        <th>Uploaded Files</th>
      </tr>
    </thead>
    <tbody>
	{% for file in attachments %}
		<tr><th>{{ file.filename }}</th></tr>
		{% endfor %}
    </tbody>
    {% endif %}
  </table>
  
	<div class="container">
	<a href="{% url 'experiment:file_list' experiment.id %}" class="btn btn-primary">Upload/Delete Files</a>
	<a href="{% url 'experiment:exp_user_list' experiment.id %}" class="btn btn-primary">View Participant Data</a>
	
	</div>
</div>
{% endblock %}

experiment/templates/experiment/experiment_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %} Create Experiment {% endblock %}

{% block content %} 
<div class="container">
<h1>
	{% if not form.instance.pk %}
	Create Experiment
	{% else %}
	Update Experiment
	{% endif %}
</h1>

	<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" name="experiment upload" class="btn btn-primary" value="Submit">
	</form>

</div>
{% endblock %}

experiment/templates/experiment/experiment_list.html
{% extends "base.html" %}
{% block title %}Experiment View{% endblock %}
{% load static %}
{% block content %}

{% block javascript %}<script type="text/javascript" src="{% static 'js/table.js' %}"></script>{% endblock %}
<div class="container">
	<h1>My Experiment List</h1>
	{% if not experiments %}
		<p>There are no experiments, please upload an experiment</p>

	{% endif %}
		<p>Upload an experiment?</p>
		<p><a href="{% url 'experiment:exp_create' %}" class="btn btn-primary">Upload</a></p>
		
			{% if experiments %}
				<div class="container">
					  <table id='tb1' class="table table-bordered table-hover">
						<thead>
						<tr>
							<th>Experiment Name</th>
							<th>Created By</th>
							<th>Experiment Description</th>
						</tr>
						</thead>
						<tbody>
						{% for experiment in request.user.experiments.all %}
						<tr onclick="location.href='{{ experiment.id }}';">
							<td >{{ experiment.name }}</td>
							<td >{{ experiment.created_By }}</td>
							<td >{{ experiment.description }}</td>
						</tr>
						{% endfor%}
						</tbody>
					</table>
				</div>
			{% endif %}
</div>
{% endblock %}

experiment/templates/experiment/experiment_list_public.html
{% extends "base.html" %}
{% block title %}Experiment Public View{% endblock %}

{% block content %}
{% load static %}
{% block javascript %}<script type="text/javascript" src="{% static 'js/table.js' %}"></script>{% endblock %}
<div class="container">
	<h1>Experiment List</h1>
		
			{% if experiments %}
				<div class="container">
					  <table id='tb1' class="table table-bordered table-hover">
						<thead>
						<tr>
							<th>Experiment Name</th>
							<th>Experiment Description</th>
						</tr>
						</thead>
						<tbody>
						{% for experiment in experiments %}
							{% if experiment.is_Published %}
								 <tr onclick="location.href='{{ experiment.id }}';">
									<td >{{ experiment.name }}</td>
									<td >{{ experiment.description }}</td>
								</tr>
							{% endif %}

						{% endfor%}
						</tbody>
					</table>
				</div>
			{% endif %}
</div>
{% endblock %}

experiment/templates/experiment/experiment_update.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %} Update Experiment {% endblock %}
{# {% block extraSrc %}<script src="{% static "js/functions.js" %}"></script> {% endblock %} #}
{% block content %} 
<div class="container">
<h1>
	Update Experiment
</h1>

	<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<!-- <input type="file" name="file_upload" value="upload"> -->
		<table class="table table-striped">
    <thead>
      <tr>
        <th>Uploaded Files</th>
      </tr>
    </thead>
    <tbody>
	{% for file in attachments %}
	<input type="hidden" name="id" value="{{ file.id }}"><tr><th>{{ file.filename }}</th>
		{% endfor %} 
    </tbody>
  </table>
  <p><a href="{% url 'experiment:file_list' experiment.id %}">to update files click here</a></p>
  
	<input type="submit" name="experiment upload" class="btn btn-primary" value="Submit">
	</form>

</div>
{% endblock %}

experiment/templates/experiment/form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send" />
</form>

experiment/templates/experiment/user_list.html
{% extends "base.html" %}
{% block title %}Participant List View{% endblock %}
{% load static %}
{% block content %}

{% block javascript %}<script type="text/javascript" src="{% static 'js/table.js' %}"></script>{% endblock %}
<div class="container">
	<h1>Participant List</h1>
	{% if not object_list and not anon_list %}
		<p>There are no particpants who have completed the experiment</p>

	{% endif %}
			{% if object_list or anon_list %}
			
				<div class="container">
					  <table id='tb1' class="table table-bordered table-hover">
						<thead>
						<tr>
							<th>Username</th>
							<th>User Type</th>
							<th>Email</th>
						</tr>
						</thead>
						<tbody>
						{% for User in object_list %}
						<tr onclick="location.href='{{ User.id }}';">
							<td >{{ User.username }}</td>
							<td >{% if User.is_participant %} Participant {% else %} Researcher {% endif %}</td>
							<td >{{ User.email }}</td>
						</tr>
						{% endfor%}
						{% for User in anon_list %}
						<tr onclick="location.href='{{ User.anon_user }}';">
							<td >{{ User.anon_user }}</td>
							<td >Anonymous</td>
							<td ></td>
						</tr>
						{% endfor%}
						</tbody>
					</table>
				</div>
			{% endif %}
</div>
{% endblock %}

experiment/templates/experiment/user_query.html
{% extends "base.html" %}
{% block title %}Participant Query Page{% endblock %}
{% load static %}
{% block content %}
<h1>Trial data of Participant</h1>


<div class="container">
{% if data %}
<div>
	<form action="{% url 'experiment:csv' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="hidden" name="table" value="{{ table }}">
	<button type="submit" name="csv" class="btn btn-default bt-sm">Download CSV File</button>	
</div>
	  <table class="table table-bordered">
		<thead>
		<tr>
			{% for key in data.keys %}
			<th>{{ key }}</th>
			{% endfor%}
		</tr>
		
		</thead>
		<tbody>
		{% for item in data.values %}
		<tr>
		{% for x in item %}
			<td >{{ x }}</td>
			{% endfor %}
		</tr>
		{% endfor %}
		</tbody>
	</table>
{% else %}
<p>No trials have been completed by user</p>
{% endif %}

</div>
{% endblock %}